[#background,reftext="Background"]
== Background

This chapter provides information common to all CMO extensions.

=== Memory and Caches

A _memory location_ is a physical resource in a system uniquely identified by a
_physical address_. The _observers_ of a given memory location consist of the
RISC-V harts or I/O devices that can access that memory location. A given
observer may not be able to access all memory locations in a system, and two
different harts or devices may or may not be able to observe the same set of
memory locations.

The physical address for a memory location may be specified by an observer
directly or may be obtained from an effective address via various translation
mechanisms.

In this specification, a _load operation_ (or _store operation_) is performed by
an observer to consume (or modify) the data at a given memory location. For a
RISC-V hart, a load or store operation may be performed as a result of an
explicit or implicit memory access. Additionally, a _read operation_ (or _write
operation_) is an operation performed on the memory location to fetch (or
update) the data at the physical resource.

****

_Load and store operations are decoupled from read and write operations by
caches, described below. For example, a load operation may be satisfied by a
cache without performing a read operation in memory, or a store operation may be
satisfied by a cache that first performs a read operation._

****

A _cache_ is a structure that buffers copies of data to reduce average memory
latency. Any number of caches may be interspersed between an observer and a
memory location, and load and store operations from an observer may be satisfied
by a cache instead of the memory location.

Caches organize copies of data into _cache blocks_, each of which represents a
contiguous, naturally aligned power-of-two (or _NAPOT_) range of memory
locations. A cache block is identified by a physical address corresponding to
the underlying memory locations, and a _cache block operation_ (or _CBO_)
operates on one or more cache blocks.

Like an operation on a memory location, a read operation may be performed on a
cache to fetch a copy of a cache block, and a write operation may be performed
on a cache to update a copy of a cache block. In effect, read and write
operations transfer copies of cache blocks among caches and memory.

The capacity and organization of a cache and the size of a cache block are both
_implementation-defined_, and the execution environment provides software a
means to discover information about the caches and cache blocks in a system. For
the initial base set of CBOs, the size of a cache block shall be uniform
throughout the system.

****

_In future CMO extensions, the requirement for a uniform cache block size may be
relaxed._

****

=== Coherent Observers

For a given memory location, a _set of coherent observers_ consists of the set
of observers for which all of the following hold without software intervention:

* Store operations from all observers in the set appear to be serialized with
  respect to each other
* Store operations from all observers in the set eventually appear to all other
  observers in the set
* A load operation from an observer in the set returns data from a store
  operation from an observer in the set (or from the initial data in memory)

The coherent observers within such a set shall access a given memory location
with the same physical address and the same physical memory attributes,
particularly coherence and cacheability.

An observer who is a member of a set of coherent observers is said to be
_coherent_ with respect to the other observers in the set. On the other hand, an
observer who is _not_ a member is said to be _non-coherent_ with respect to the
observers in the set.

Caches introduce multiple copies of a given cache block, and the copies accessed
by the coherent observers are kept coherent by an _implementation-defined_
mechanism. A _coherent cache_ may allocate a copy of the cache block at any
time, obtaining a copy from another coherent cache or from the underlying memory
locations by performing a read operation. Similarly, a coherent cache may
deallocate a copy of the cache block at any time, transferring a copy to another
coherent cache by performing a write operation. Additionally, a coherent cache
may transfer a copy of the cache block to the underlying memory locations at any
time by performing a write operation, provided that a coherent observer
performed a store operation to the cache block since the previous write
operation to the memory locations. In the absence of an invalidate operation
performed by a coherent observer (see <<#Zicbom>>), at least one coherent cache
shall write the cache block to the underlying memory locations if a coherent
observer performed a store operation to the cache block; otherwise, no coherent
cache may perform a write operation of the cache block to the underlying memory
locations.

****

_The above restrictions ensure that a "clean" copy cannot be written back into
memory._

****

=== Memory Ordering

==== Preserved Program Order

The preserved program order (abbreviated _PPO_) rules are defined by the RVWMO
memory ordering model. How the operations resulting from CMO instructions fit
into these rules is described below.

For cache block management instructions, the resulting invalidate, clean, and
flush operations behave as stores in the PPO rules subject to one additional
overlapping address rule. Specifically, if _a_ precedes _b_ in program order,
then _a_ will precede _b_ in the global memory order if:

* _a_ is an invalidate, clean, or flush, _b_ is a load, and _a_ and _b_ access
  overlapping memory addresses

****

_The above rule ensures that a subsequent load in program order never appears
in the global memory order before a preceding invalidate, clean, or flush
operation to an overlapping address._

****

Additionally, invalidate, clean, and flush operations are classified as W or O
(depending on the physical memory attributes for the corresponding physical
addresses) for the purposes of predecessor and successor sets in `FENCE`
instructions.

For cache block zero instructions, the resulting store operations simply 
behave as stores in the PPO rules.

Finally, as cache block prefetch instructions do not modify architectural memory
state, the resulting operations are _not_ ordered by the PPO rules.

==== Load Values (FIXME)

In addition, an invalidate operation changes the set of values that may be 
returned by a load. In particular, a third condition is added to the Load Value 
Axiom:

[start=3]
. If an invalidate precedes _i_ in program order and operates on a byte, and no 
  store to that byte appears in program order or in the global memory order 
  between the invalidate and _i_, the load value is _implementation-defined_

=== Traps

==== Illegal Instruction and Virtual Instruction Exceptions

Cache block management instructions and cache block zero instructions may take
an illegal instruction exception depending on the _current privilege mode_ and
the state of the CMO control registers described in the <<#csr_state>> section.
The current privilege mode refers to the privilege mode of the hart at the time
the instruction is executed.

Cache block prefetch instructions do _not_ take illegal instruction exceptions.

Additionally, CMO instructions do _not_ take virtual instruction exceptions.

==== Page Fault and Guest-Page Fault Exceptions

During address translation, CMO instructions may take a page fault depending on
the type of instruction, the _effective privilege mode_ (as determined by the
`MPRV`, `MPV`, and `MPP` bits in `mstatus`) of the resulting access, and the
permissions granted by the page table entry (PTE). If two-stage address
translation is enabled, CMO instructions may also take a guest-page fault.

Cache block management instructions require a valid leaf translation
(`V=1` and `RWX` encoding not "_Reserved for future use._") and,
if applicable, user access (`U=1`) in the effective privilege mode.
If the required conditions are _not_ met, the instruction takes
a store/AMO page fault exception.

Cache block zero instructions require a valid leaf translation
(`V=1` and `RWX` encoding not "_Reserved for future use._")
and write (`W=1`) permission and,
if applicable, user access (`U=1`) in the effective privilege mode.
If the required conditions are _not_ met, the instruction takes
a store/AMO page fault exception.

If G-stage address translation is enabled, the above instructions take a 
store/AMO guest-page fault if the G-stage PTE does _not_ allow the access.

Cache block prefetch instructions require a valid leaf translation
(`V=1` and `RWX` encoding not "_Reserved for future use._") and,
if applicable, user access (`U=1`) in the effective privilege mode.
In addition, it is _implementation-defined_ whether any of the following are
required to perform a memory access:

* `PREFETCH.R` requires read (`R=1`) permission
* `PREFETCH.W` requires write (`W=1`) permission
* `PREFETCH.I` requires execute (`X=1`) permission

If the required conditions are _not_ met, however, the instruction does _not_
take a page fault or guest-page fault exception and retires without performing a
memory access.

===== Effect of other `xstatus` bits

The `mstatus.MXR` bit (also `sstatus.MXR`) and the `vsstatus.MXR` bit do _not_
affect the execution of CMO instructions.

The `mstatus.SUM` bit (also `sstatus.SUM`) and the `vsstatus.SUM` bit do _not_
affect the execution of CMO instructions beyond modifying permissions for
S/HS-mode and VS-mode accesses as specified by the privileged architecture.

==== Access Fault Exception

A CMO instruction may take an access fault exception, as detailed in the
privileged architecture specification, that interrupts the address translation
process. Assuming the address translation process completes with a valid
translation, a CMO instruction may also take an access fault exception depending
on the type of instruction, the effective privilege mode of the resulting
access, and the permissions granted by the physical memory protection (PMP) unit
and the physical memory attributes (PMAs).

****

_For now, we assume two things about PMAs:_

. _PMAs are the same for all physical addresses in a cache block_
. _Memory that can be cached cannot be write-only_

****

Read (`R`), write (`W`), and execute (`X`) permissions are granted by the PMP
and the PMAs. Although the PMP may grant different permissions to different
physical addresses in a cache block, the PMAs for a cache block shall be the
same for _all_ physical addresses in the cache block and read permission shall
be granted if write permission has been granted. If these PMA constraints are
_not_ met, the behavior of a CMO instruction is UNSPECIFIED.

For the purposes of access fault determination, the following terms are defined
for a given physical address:

* _joint read permission_ is granted when both the PMP and PMAs allow read
  access to the physical address
* _joint write permission_ is granted when both the PMP and PMAs allow write
  access to the physical address
* _joint execute permission_ is granted when both the PMP and PMAs allow execute
  access to the physical address

Cache block management instructions require either joint read permission or
joint execute permission for each physical address in a cache block. If the
required condition is _not_ met, the instruction takes a store/AMO access fault
exception.

Cache block zero instructions require joint write permission for each physical
address in a cache block. If the required condition is _not_ met, the
instruction takes a store/AMO access fault exception.

Cache block prefetch instructions require either joint read permission or joint
execute permission for each physical address in a cache block. In addition, it
is _implementation-defined_ whether any of the following are required to perform
a memory access:

* `PREFETCH.R` requires joint read permission
* `PREFETCH.W` requires joint write permission
* `PREFETCH.I` requires joint execute permission

If the required conditions are _not_ met, however, the instruction does _not_
take an access fault exception and retires without performing a memory access.

==== Address Misaligned Exception

CMO instructions do _not_ generate address misaligned exceptions.

==== Breakpoint Exception

CMO instructions may generate breakpoint exceptions (or may cause other debug
actions) subject to the general trigger module behaviors specified in the debug
architecture. When `type=2` (i.e. `mcontrol`), the behavior of a trigger for
load and store address matches is UNSPECIFIED for CMO instructions. When
`type=6` (i.e. `mcontrol6`), the behavior of a trigger for load and store
address matches is based on the following classification of a CMO instruction:

* A cache block management instruction is both a load and a store
* A cache block zero instruction is a store 
* It is _implementation-defined_ whether a cache block prefetch instruction is
  both a load and a store or neither a load nor a store

Load and store data matches for all CMO instructions are UNSPECIFIED.

****

_An implementation may convert cache block hint instructions into NOPs prior to
executing the instruction. Load and store matches are not applicable in such an
implementation._

_For load and store address matches on a CMO effective address, software should 
program the trigger to match on NAPOT ranges, i.e. `mcontrol6.match=1`, and 
should program the NAPOT range to equal the cache block size._

****

=== Effects on Constrained LR/SC Loops

Executing a `CBO.INVAL`, `CBO.FLUSH`, `CBO.ZERO`, or `PREFETCH.W` instruction
may cause a reservation on another hart to be lost. As a result, executing one
of these instructions constitutes an additional event (like executing an
unconditional store or AMO instruction) that satisfies the system forward
progress requirements of constrained LR/SC loops.
