[#csr_state,reftext="Control and Status Register State"]
== Control and Status Register State

Three CSRs control execution of CMO instructions:

* `m{csrname}`
* `s{csrname}`
* `h{csrname}`

****

_The `s{csrname}` register is used by all supervisor modes, including VS-mode. A
hypervisor is responsible for saving and restoring `s{csrname}` on guest context
switches._

****

The `h{csrname}` register is only present if the H-extension is implemented and
enabled.

Each `x{csrname}` register (where `x` is `m`, `s`, or `h`) has the following
generic format:

.Generic Format for x{csrname} CSRs
[cols="^10,^10,80a"]
|===
| Bits    | Name     | Description

| [??:??] | `CBIE`   | Cache Block Invalidate instruction Enable

Enables the execution of the cache block invalidate instruction, `CBO.INVAL`, in
a lower privilege mode:

* `00`: The instruction takes an illegal instruction exception
* `01`: The instruction is executed and performs a flush operation
* `10`: _Reserved_ (implementations are expected, but not required, to treat
  this value as `00`; however, software must not rely on this behavior)
* `11`: The instruction is executed and performs an invalidate operation

| [??]    | `CBCFE`  | Cache Block Clean and Flush instruction Enable

Enables the execution of the cache block clean instruction, `CBO.CLEAN`, and the
cache block flush instruction, `CBO.FLUSH`, in a lower privilege mode:

* `0`: The instruction takes an illegal instruction exception
* `1`: The instruction is executed

| [??]    | `CBZE`   | Cache Block Zero instruction Enable

Enables the execution of the cache block zero instruction, `CBO.ZERO`, in a
lower privilege mode:

* `0`: The instruction takes an illegal instruction exception
* `1`: The instruction is executed

|===

The x{csrname} registers control CMO instruction execution based on the _current
privilege mode_ and the state of the appropriate CSRs, as detailed below.

A cache block invalidate instruction executes or takes an illegal instruction
exception based on the state of the `x{csrname}.CBIE` fields:

[source,sail,subs="attributes+"]
--

// this pseudocode assumes the expected implementation of the reserved encoding
if (((curr_priv_mode == S/HS) && m{csrname}.CBIE[0]) ||
    ((curr_priv_mode == U)    && m{csrname}.CBIE[0] && s{csrname}.CBIE[0]) ||
    ((curr_priv_mode == VS)   && m{csrname}.CBIE[0] && h{csrname}.CBIE[0]) ||
    ((curr_priv_mode == VU)   &&
     m{csrname}.CBIE[0] && s{csrname}.CBIE[0] && h{csrname}.CBIE[0]))
{
  if (((curr_priv_mode == S/HS) && m{csrname}.CBIE[1]) ||
      ((curr_priv_mode == U)    && m{csrname}.CBIE[1] && s{csrname}.CBIE[1]) ||
      ((curr_priv_mode == VS)   && m{csrname}.CBIE[1] && h{csrname}.CBIE[1]) ||
      ((curr_priv_mode == VU)   &&
       m{csrname}.CBIE[1] && s{csrname}.CBIE[1] && h{csrname}.CBIE[1]))
  {
    <execute CBO.INVAL and perform an invalidate operation>
  } else {
    <execute CBO.INVAL and perform a flush operation
  }
}
else
{
  <illegal instruction trap>
}

--

****

_Until a modified cache block has updated memory, a `CBO.INVAL` instruction may
expose stale data values in memory if the CSRs are programmed to perform an
invalidate operation. This behavior may result in a security hole if lower
privileged level software performs an invalidate operation and accesses
sensitive information in memory._

_To avoid such holes, higher privileged level software must perform either a
clean or flush operation on the cache block before permitting lower privileged
level software to perform an invalidate operation on the block. Alternatively,
higher privileged level software may program the CSRs so that `CBO.INVAL`
either traps or performs a flush operation in a lower privileged level._

****

A cache block clean or flush instruction executes or takes an illegal
instruction exception based on the state of the `x{csrname}.CBCFE` bits:

[source,sail,subs="attributes+"]
--

if (((curr_priv_mode == S/HS) && m{csrname}.CBCFE) ||
    ((curr_priv_mode == U)    && m{csrname}.CBCFE && s{csrname}.CBCFE) ||
    ((curr_priv_mode == VS)   && m{csrname}.CBCFE && h{csrname}.CBCFE) ||
    ((curr_priv_mode == VU)   &&
     m{csrname}.CBCFE && s{csrname}.CBCFE && h{csrname}.CBCFE))
{
  <execute CBO.CLEAN or CBO.FLUSH>
}
else
{
  <illegal instruction trap>
}

--

Finally, a cache block zero instruction executes or takes an illegal instruction
exception based on the state of the `x{csrname}.CBZE` bits:

[source,sail,subs="attributes+"]
--

if (((curr_priv_mode == S/HS) && m{csrname}.CBZE) ||
    ((curr_priv_mode == U)    && m{csrname}.CBZE && s{csrname}.CBZE) ||
    ((curr_priv_mode == VS)   && m{csrname}.CBZE && h{csrname}.CBZE) ||
    ((curr_priv_mode == VU)   &&
     m{csrname}.CBZE && s{csrname}.CBZE && h{csrname}.CBZE))
{
  <execute CBO.ZERO>
}
else
{
  <illegal instruction trap>
}

--

Each `x{csrname}` register is WARL, where a CSR read returns the behaviors
supported by the implementation.
