[#intro,reftext="Introduction"]
== Introduction

_Cache management operation_ (or _CMO_) instructions perform operations on
cached copies of data in the memory hierarchy. These instructions are grouped by
operation into the following instruction classes:

* A _management_ instruction manipulates cached copies of data with respect to
  sets of observers
* A _zero_ instruction zeros out a range of memory locations, potentially
  allocating cached copies of data in one or more caches
* A _prefetch_ instruction indicates to hardware that data at a given memory
  location may be accessed in the near future, potentially allocating cached
  copies of data in one or more caches

This document introduces a base set of CMO ISA extensions that operate
specifically on cache blocks. Each of the above classes of instructions
represents an extension in this specification:

* The _Zicbom_ extension defines a set of cache block management instructions:
  `CBO.INVAL`, `CBO.CLEAN`,  and `CBO.FLUSH`
* The _Zicboz_ extension defines a cache block zero instruction: `CBO.ZERO`
* The _Zicbop_ extension defines a set of cache block prefetch instructions:
  `PREFETCH.R`, `PREFETCH.W`, and `PREFETCH.I`

The execution behavior of the above instructions is also modified by CSR state
added by this specification.

The remainder of this document provides general background information on CMO
instructions and describes each of the above ISA extensions.

****

_The term CMO encompasses all operations on caches or resources related to
caches. The term CBO represents a subset of CMOs that operate only on cache
blocks. The first CMO extensions only define CBOs._

****
